// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsljcorhhnushvbvsrmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbGpjb3JoaG51c2h2YnZzcm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTA1NzksImV4cCI6MjA3MzYyNjU3OX0.-ilw64YADRBXVW3KPKNUxCOEZepXYnL1L-lsj3C4-_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});